all: false
template: testify
template-data:
  unroll-variadic: true
filename: "zz_generated.{{.InterfaceName}}.go"
formatter: goimports

packages:
  github.com/alexandremahdhaoui/forge-register/internal/adapter/storeadapter:
    config:
      dir: internal/mocks/storeadaptermock
      pkgname: storeadaptermock
    interfaces:
      Store:

  github.com/alexandremahdhaoui/forge-register/internal/adapter/engineadapter:
    config:
      dir: internal/mocks/engineadaptermock
      pkgname: engineadaptermock
    interfaces:
      Caller:

  github.com/alexandremahdhaoui/forge-register/internal/adapter/registryadapter:
    config:
      dir: internal/mocks/registryadaptermock
      pkgname: registryadaptermock
    interfaces:
      Lister:

  github.com/alexandremahdhaoui/forge-register/internal/adapter/osvadapter:
    config:
      dir: internal/mocks/osvadaptermock
      pkgname: osvadaptermock
    interfaces:
      Querier:

  github.com/alexandremahdhaoui/forge-register/internal/controller/discoverycontroller:
    config:
      dir: internal/mocks/discoverycontrollermock
      pkgname: discoverycontrollermock
    interfaces:
      Discoverer:
