// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package registryadaptermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-register/internal/types/regtypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLister creates a new instance of MockLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLister {
	mock := &MockLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLister is an autogenerated mock type for the Lister type
type MockLister struct {
	mock.Mock
}

type MockLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLister) EXPECT() *MockLister_Expecter {
	return &MockLister_Expecter{mock: &_m.Mock}
}

// Versions provides a mock function for the type MockLister
func (_mock *MockLister) Versions(ctx context.Context, ecosystem string, pkg string) ([]regtypes.Candidate, error) {
	ret := _mock.Called(ctx, ecosystem, pkg)

	if len(ret) == 0 {
		panic("no return value specified for Versions")
	}

	var r0 []regtypes.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]regtypes.Candidate, error)); ok {
		return returnFunc(ctx, ecosystem, pkg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []regtypes.Candidate); ok {
		r0 = returnFunc(ctx, ecosystem, pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]regtypes.Candidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ecosystem, pkg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLister_Versions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Versions'
type MockLister_Versions_Call struct {
	*mock.Call
}

// Versions is a helper method to define mock.On call
//   - ctx context.Context
//   - ecosystem string
//   - pkg string
func (_e *MockLister_Expecter) Versions(ctx any, ecosystem any, pkg any) *MockLister_Versions_Call {
	return &MockLister_Versions_Call{Call: _e.mock.On("Versions", ctx, ecosystem, pkg)}
}

func (_c *MockLister_Versions_Call) Run(run func(ctx context.Context, ecosystem string, pkg string)) *MockLister_Versions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLister_Versions_Call) Return(candidates []regtypes.Candidate, err error) *MockLister_Versions_Call {
	_c.Call.Return(candidates, err)
	return _c
}

func (_c *MockLister_Versions_Call) RunAndReturn(run func(ctx context.Context, ecosystem string, pkg string) ([]regtypes.Candidate, error)) *MockLister_Versions_Call {
	_c.Call.Return(run)
	return _c
}
