#!/bin/sh
set -eu

go run ./cmd/docgen >/dev/null

if ! git diff --quiet -- docs/concepts.md docs/decisions.md 'cmd/*/docs'; then
    echo "generated docs are stale. run: go run ./cmd/docgen" >&2
    git --no-pager diff --stat -- docs/concepts.md docs/decisions.md 'cmd/*/docs' >&2
    exit 1
fi

fail=0

for f in docs/concepts.md docs/decisions.md cmd/ci-*/docs/usage.md cmd/ci-*/docs/schema.md; do
    if ! head -1 "$f" | grep -q "Code generated by docgen"; then
        echo "$f has no generated header, so nothing stops a human editing it" >&2
        fail=1
    fi
done

for f in README.md docs/architecture.md; do
    if head -1 "$f" | grep -q "Code generated"; then
        echo "$f claims to be generated but it is the hand written guide" >&2
        fail=1
    fi
done

if [ "$fail" -eq 0 ]; then
    echo "generated docs are current, and only the README and the guide are hand written"
fi

exit "$fail"
