#!/bin/sh
set -eu

# What this gate means changed on 2026-08-19. It used to prove this repo builds
# from a lone clone. go.mod is generated by forge-factory now and no longer
# committed, so a lone clone has no manifest at all. It proves the repo builds
# from a synced workspace instead.
#
# It is not deleted. Four tags shipped from an incomplete go.sum and nothing
# caught it, which is what this gate exists for.

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

if [ ! -f go.mod ]; then
    echo "no go.mod. run: forge-factory sync" >&2
    echo "a member is built through the workspace, never cloned and built alone" >&2
    exit 1
fi

if ! head -1 go.mod | grep -q "Generated by forge-factory"; then
    echo "go.mod is not the generated one. run: forge-factory sync" >&2
    exit 1
fi

cp go.mod go.sum "$TMP/"

# GOWORK=off is the point. The workspace lends sums from siblings, so a build
# that only ever runs inside it never proves this module resolves on its own.
if ! GOWORK=off GOFLAGS= go build ./... >"$TMP/build.log" 2>&1; then
    echo "this repo does not build from its own generated go.mod" >&2
    head -10 "$TMP/build.log" >&2
    exit 1
fi

GOWORK=off go mod tidy >/dev/null 2>&1

if ! cmp -s go.mod "$TMP/go.mod" || ! cmp -s go.sum "$TMP/go.sum"; then
    diff -u "$TMP/go.mod" go.mod >&2 || true
    diff -u "$TMP/go.sum" go.sum >&2 || true
    cp "$TMP/go.mod" go.mod
    cp "$TMP/go.sum" go.sum
    echo "go.mod or go.sum is not tidy. run: forge-factory sync" >&2
    exit 1
fi

echo "builds and resolves from the generated manifest, and go.mod and go.sum are tidy"
