// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package osvadaptermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-register/internal/types/regtypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Vulns provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Vulns(ctx context.Context, ecosystem string, pkg string, versions []string) (map[string][]regtypes.Vuln, string, error) {
	ret := _mock.Called(ctx, ecosystem, pkg, versions)

	if len(ret) == 0 {
		panic("no return value specified for Vulns")
	}

	var r0 map[string][]regtypes.Vuln
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) (map[string][]regtypes.Vuln, string, error)); ok {
		return returnFunc(ctx, ecosystem, pkg, versions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) map[string][]regtypes.Vuln); ok {
		r0 = returnFunc(ctx, ecosystem, pkg, versions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]regtypes.Vuln)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) string); ok {
		r1 = returnFunc(ctx, ecosystem, pkg, versions)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, []string) error); ok {
		r2 = returnFunc(ctx, ecosystem, pkg, versions)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQuerier_Vulns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Vulns'
type MockQuerier_Vulns_Call struct {
	*mock.Call
}

// Vulns is a helper method to define mock.On call
//   - ctx context.Context
//   - ecosystem string
//   - pkg string
//   - versions []string
func (_e *MockQuerier_Expecter) Vulns(ctx any, ecosystem any, pkg any, versions any) *MockQuerier_Vulns_Call {
	return &MockQuerier_Vulns_Call{Call: _e.mock.On("Vulns", ctx, ecosystem, pkg, versions)}
}

func (_c *MockQuerier_Vulns_Call) Run(run func(ctx context.Context, ecosystem string, pkg string, versions []string)) *MockQuerier_Vulns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQuerier_Vulns_Call) Return(stringToVulns map[string][]regtypes.Vuln, s string, err error) *MockQuerier_Vulns_Call {
	_c.Call.Return(stringToVulns, s, err)
	return _c
}

func (_c *MockQuerier_Vulns_Call) RunAndReturn(run func(ctx context.Context, ecosystem string, pkg string, versions []string) (map[string][]regtypes.Vuln, string, error)) *MockQuerier_Vulns_Call {
	_c.Call.Return(run)
	return _c
}
