// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package engineadaptermock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCaller creates a new instance of MockCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaller {
	mock := &MockCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCaller is an autogenerated mock type for the Caller type
type MockCaller struct {
	mock.Mock
}

type MockCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaller) EXPECT() *MockCaller_Expecter {
	return &MockCaller_Expecter{mock: &_m.Mock}
}

// Call provides a mock function for the type MockCaller
func (_mock *MockCaller) Call(ctx context.Context, uri string, tool string, in any, out any) error {
	ret := _mock.Called(ctx, uri, tool, in, out)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any, any) error); ok {
		r0 = returnFunc(ctx, uri, tool, in, out)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCaller_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockCaller_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
//   - tool string
//   - in any
//   - out any
func (_e *MockCaller_Expecter) Call(ctx any, uri any, tool any, in any, out any) *MockCaller_Call_Call {
	return &MockCaller_Call_Call{Call: _e.mock.On("Call", ctx, uri, tool, in, out)}
}

func (_c *MockCaller_Call_Call) Run(run func(ctx context.Context, uri string, tool string, in any, out any)) *MockCaller_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCaller_Call_Call) Return(err error) *MockCaller_Call_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCaller_Call_Call) RunAndReturn(run func(ctx context.Context, uri string, tool string, in any, out any) error) *MockCaller_Call_Call {
	_c.Call.Return(run)
	return _c
}
