// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storeadaptermock

import (
	"context"

	"github.com/alexandremahdhaoui/forge-register/internal/types/regtypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// PendingRequests provides a mock function for the type MockStore
func (_mock *MockStore) PendingRequests(ctx context.Context) (map[string]regtypes.Request, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PendingRequests")
	}

	var r0 map[string]regtypes.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]regtypes.Request, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]regtypes.Request); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]regtypes.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PendingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingRequests'
type MockStore_PendingRequests_Call struct {
	*mock.Call
}

// PendingRequests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) PendingRequests(ctx any) *MockStore_PendingRequests_Call {
	return &MockStore_PendingRequests_Call{Call: _e.mock.On("PendingRequests", ctx)}
}

func (_c *MockStore_PendingRequests_Call) Run(run func(ctx context.Context)) *MockStore_PendingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_PendingRequests_Call) Return(stringToRequest map[string]regtypes.Request, err error) *MockStore_PendingRequests_Call {
	_c.Call.Return(stringToRequest, err)
	return _c
}

func (_c *MockStore_PendingRequests_Call) RunAndReturn(run func(ctx context.Context) (map[string]regtypes.Request, error)) *MockStore_PendingRequests_Call {
	_c.Call.Return(run)
	return _c
}

// PutRequest provides a mock function for the type MockStore
func (_mock *MockStore) PutRequest(ctx context.Context, key string, request regtypes.Request) error {
	ret := _mock.Called(ctx, key, request)

	if len(ret) == 0 {
		panic("no return value specified for PutRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, regtypes.Request) error); ok {
		r0 = returnFunc(ctx, key, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PutRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRequest'
type MockStore_PutRequest_Call struct {
	*mock.Call
}

// PutRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - request regtypes.Request
func (_e *MockStore_Expecter) PutRequest(ctx any, key any, request any) *MockStore_PutRequest_Call {
	return &MockStore_PutRequest_Call{Call: _e.mock.On("PutRequest", ctx, key, request)}
}

func (_c *MockStore_PutRequest_Call) Run(run func(ctx context.Context, key string, request regtypes.Request)) *MockStore_PutRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 regtypes.Request
		if args[2] != nil {
			arg2 = args[2].(regtypes.Request)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_PutRequest_Call) Return(err error) *MockStore_PutRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PutRequest_Call) RunAndReturn(run func(ctx context.Context, key string, request regtypes.Request) error) *MockStore_PutRequest_Call {
	_c.Call.Return(run)
	return _c
}

// PutTrack provides a mock function for the type MockStore
func (_mock *MockStore) PutTrack(ctx context.Context, track regtypes.Track) error {
	ret := _mock.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for PutTrack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, regtypes.Track) error); ok {
		r0 = returnFunc(ctx, track)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PutTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTrack'
type MockStore_PutTrack_Call struct {
	*mock.Call
}

// PutTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - track regtypes.Track
func (_e *MockStore_Expecter) PutTrack(ctx any, track any) *MockStore_PutTrack_Call {
	return &MockStore_PutTrack_Call{Call: _e.mock.On("PutTrack", ctx, track)}
}

func (_c *MockStore_PutTrack_Call) Run(run func(ctx context.Context, track regtypes.Track)) *MockStore_PutTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 regtypes.Track
		if args[1] != nil {
			arg1 = args[1].(regtypes.Track)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PutTrack_Call) Return(err error) *MockStore_PutTrack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PutTrack_Call) RunAndReturn(run func(ctx context.Context, track regtypes.Track) error) *MockStore_PutTrack_Call {
	_c.Call.Return(run)
	return _c
}

// PutVerdict provides a mock function for the type MockStore
func (_mock *MockStore) PutVerdict(ctx context.Context, key string, verdict regtypes.Verdict) error {
	ret := _mock.Called(ctx, key, verdict)

	if len(ret) == 0 {
		panic("no return value specified for PutVerdict")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, regtypes.Verdict) error); ok {
		r0 = returnFunc(ctx, key, verdict)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PutVerdict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutVerdict'
type MockStore_PutVerdict_Call struct {
	*mock.Call
}

// PutVerdict is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - verdict regtypes.Verdict
func (_e *MockStore_Expecter) PutVerdict(ctx any, key any, verdict any) *MockStore_PutVerdict_Call {
	return &MockStore_PutVerdict_Call{Call: _e.mock.On("PutVerdict", ctx, key, verdict)}
}

func (_c *MockStore_PutVerdict_Call) Run(run func(ctx context.Context, key string, verdict regtypes.Verdict)) *MockStore_PutVerdict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 regtypes.Verdict
		if args[2] != nil {
			arg2 = args[2].(regtypes.Verdict)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_PutVerdict_Call) Return(err error) *MockStore_PutVerdict_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PutVerdict_Call) RunAndReturn(run func(ctx context.Context, key string, verdict regtypes.Verdict) error) *MockStore_PutVerdict_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function for the type MockStore
func (_mock *MockStore) Track(ctx context.Context, ecosystem string, pkg string, prefix string) (regtypes.Track, bool, error) {
	ret := _mock.Called(ctx, ecosystem, pkg, prefix)

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 regtypes.Track
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (regtypes.Track, bool, error)); ok {
		return returnFunc(ctx, ecosystem, pkg, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) regtypes.Track); ok {
		r0 = returnFunc(ctx, ecosystem, pkg, prefix)
	} else {
		r0 = ret.Get(0).(regtypes.Track)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) bool); ok {
		r1 = returnFunc(ctx, ecosystem, pkg, prefix)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, ecosystem, pkg, prefix)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStore_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockStore_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - ctx context.Context
//   - ecosystem string
//   - pkg string
//   - prefix string
func (_e *MockStore_Expecter) Track(ctx any, ecosystem any, pkg any, prefix any) *MockStore_Track_Call {
	return &MockStore_Track_Call{Call: _e.mock.On("Track", ctx, ecosystem, pkg, prefix)}
}

func (_c *MockStore_Track_Call) Run(run func(ctx context.Context, ecosystem string, pkg string, prefix string)) *MockStore_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Track_Call) Return(track regtypes.Track, b bool, err error) *MockStore_Track_Call {
	_c.Call.Return(track, b, err)
	return _c
}

func (_c *MockStore_Track_Call) RunAndReturn(run func(ctx context.Context, ecosystem string, pkg string, prefix string) (regtypes.Track, bool, error)) *MockStore_Track_Call {
	_c.Call.Return(run)
	return _c
}

// Tracks provides a mock function for the type MockStore
func (_mock *MockStore) Tracks(ctx context.Context) ([]regtypes.Track, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Tracks")
	}

	var r0 []regtypes.Track
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]regtypes.Track, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []regtypes.Track); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]regtypes.Track)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Tracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracks'
type MockStore_Tracks_Call struct {
	*mock.Call
}

// Tracks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Tracks(ctx any) *MockStore_Tracks_Call {
	return &MockStore_Tracks_Call{Call: _e.mock.On("Tracks", ctx)}
}

func (_c *MockStore_Tracks_Call) Run(run func(ctx context.Context)) *MockStore_Tracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Tracks_Call) Return(tracks []regtypes.Track, err error) *MockStore_Tracks_Call {
	_c.Call.Return(tracks, err)
	return _c
}

func (_c *MockStore_Tracks_Call) RunAndReturn(run func(ctx context.Context) ([]regtypes.Track, error)) *MockStore_Tracks_Call {
	_c.Call.Return(run)
	return _c
}

// TracksOf provides a mock function for the type MockStore
func (_mock *MockStore) TracksOf(ctx context.Context, ecosystem string, pkg string) ([]regtypes.Track, error) {
	ret := _mock.Called(ctx, ecosystem, pkg)

	if len(ret) == 0 {
		panic("no return value specified for TracksOf")
	}

	var r0 []regtypes.Track
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]regtypes.Track, error)); ok {
		return returnFunc(ctx, ecosystem, pkg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []regtypes.Track); ok {
		r0 = returnFunc(ctx, ecosystem, pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]regtypes.Track)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ecosystem, pkg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_TracksOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TracksOf'
type MockStore_TracksOf_Call struct {
	*mock.Call
}

// TracksOf is a helper method to define mock.On call
//   - ctx context.Context
//   - ecosystem string
//   - pkg string
func (_e *MockStore_Expecter) TracksOf(ctx any, ecosystem any, pkg any) *MockStore_TracksOf_Call {
	return &MockStore_TracksOf_Call{Call: _e.mock.On("TracksOf", ctx, ecosystem, pkg)}
}

func (_c *MockStore_TracksOf_Call) Run(run func(ctx context.Context, ecosystem string, pkg string)) *MockStore_TracksOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_TracksOf_Call) Return(tracks []regtypes.Track, err error) *MockStore_TracksOf_Call {
	_c.Call.Return(tracks, err)
	return _c
}

func (_c *MockStore_TracksOf_Call) RunAndReturn(run func(ctx context.Context, ecosystem string, pkg string) ([]regtypes.Track, error)) *MockStore_TracksOf_Call {
	_c.Call.Return(run)
	return _c
}

// Verdict provides a mock function for the type MockStore
func (_mock *MockStore) Verdict(ctx context.Context, key string) (regtypes.Verdict, bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Verdict")
	}

	var r0 regtypes.Verdict
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (regtypes.Verdict, bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) regtypes.Verdict); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(regtypes.Verdict)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStore_Verdict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verdict'
type MockStore_Verdict_Call struct {
	*mock.Call
}

// Verdict is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStore_Expecter) Verdict(ctx any, key any) *MockStore_Verdict_Call {
	return &MockStore_Verdict_Call{Call: _e.mock.On("Verdict", ctx, key)}
}

func (_c *MockStore_Verdict_Call) Run(run func(ctx context.Context, key string)) *MockStore_Verdict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Verdict_Call) Return(verdict regtypes.Verdict, b bool, err error) *MockStore_Verdict_Call {
	_c.Call.Return(verdict, b, err)
	return _c
}

func (_c *MockStore_Verdict_Call) RunAndReturn(run func(ctx context.Context, key string) (regtypes.Verdict, bool, error)) *MockStore_Verdict_Call {
	_c.Call.Return(run)
	return _c
}
